using SwipeIT.Models;
using SwipeIT.ViewModels;
using System.Collections.Generic;
using System.Collections.ObjectModel;

namespace SwipeIT.Services
{
    public class MockData
    {
        private IEnumerable<Developer> developers;
        private IEnumerable<Recruiter> recruiters;
        private IEnumerable<Admin> admins;
        private IEnumerable<Skill> skills;

        public MockData()
        {
            MakeDeveloperList();
            MakeRecruiterList();
            MakeAdminList();
            MakeSkillList();
        }

        private void MakeDeveloperList()
        {
            developers = new List<Developer>
            {
                new Developer {LastName = "Van Gelder",FirstName = "Jens",Image = "Icon15.png",Skills = new ObservableCollection<Skill>{new Skill{SkillName="C#"},new Skill{SkillName=".NET"},},AvailableLocations = new ObservableCollection<AvailableLocation>{new AvailableLocation{Province = Province.Antwerpen },new AvailableLocation{Province = Province.VlaamsBrabant},new AvailableLocation{Province = Province.Luik},new AvailableLocation{Province = Province.Henegouwen},},Email ="jens.v.gelder@gmail.com",Password ="pass",Address = "Haacht neerstraat",},
                new Developer {LastName = "Maes",FirstName = "Dries",Image = "Icon03.png",Skills = new ObservableCollection<Skill>{new Skill{SkillName="C#"},new Skill{SkillName=".NET"},},AvailableLocations = new ObservableCollection<AvailableLocation>{new AvailableLocation{Province = Province.Antwerpen},new AvailableLocation{Province = Province.VlaamsBrabant},new AvailableLocation{Province = Province.Henegouwen },},Email="dm.inbox@outlook.com",Password ="pass"},
                new Developer {LastName = "Impe",FirstName = "Ward",Image = "Icon07.png",Skills = new ObservableCollection<Skill>{new Skill{SkillName="C#"},},AvailableLocations = new ObservableCollection<AvailableLocation>{new AvailableLocation{Province = Province.Antwerpen},new AvailableLocation{Province = Province.VlaamsBrabant},new AvailableLocation{Province = Province.Henegouwen},},Email="ward@impesoft.com",Password ="pass"},
                new Developer {LastName = "Kesteloot",FirstName = "Sebastiaan-Willem",Image = "Icon05.png",Skills = new ObservableCollection<Skill>{new Skill{SkillName="C#"},new Skill{SkillName=".NET"},},AvailableLocations = new ObservableCollection<AvailableLocation>{new AvailableLocation{Province = Province.Antwerpen},new AvailableLocation{Province = Province.VlaamsBrabant},new AvailableLocation{Province = Province.Henegouwen},},Email ="feugiat.metus@Donecegestas.co.uk",Password="pass"},
                new Developer {LastName = "Van Tittelboom",FirstName = "Simon",Image = "Icon06.png",Skills = new ObservableCollection<Skill>{new Skill{SkillName="C#"},new Skill{SkillName="Javascript"},},AvailableLocations = new ObservableCollection<AvailableLocation>{new AvailableLocation{Province = Province.Antwerpen},new AvailableLocation{Province = Province.VlaamsBrabant},new AvailableLocation{Province = Province.Henegouwen},},Email="feugiat.metus@Donecegestas.co.uk",Password ="pass"},new Developer {LastName = "Alfvoet",FirstName = "Joyce",Image = "Icon08.png",Skills = new ObservableCollection<Skill>{new Skill{SkillName="C#"},},AvailableLocations = new ObservableCollection<AvailableLocation>{new AvailableLocation{Province = Province.Antwerpen},new AvailableLocation{Province = Province.VlaamsBrabant},new AvailableLocation{Province = Province.Henegouwen},},Email ="joyce.alfvoet@gmail.com",Password = "pass"},
                new Developer {LastName = "DeLobelle",FirstName = "Kobe",Image = "Icon10.png",Skills = new ObservableCollection<Skill>{new Skill{SkillName="C#"},new Skill{SkillName=".NET"},},AvailableLocations = new ObservableCollection<AvailableLocation>{new AvailableLocation{Province = Province.Antwerpen},new AvailableLocation{Province = Province.VlaamsBrabant},new AvailableLocation{Province = Province.Henegouwen},},Email = "feugiat.metus@Donecegestas.co.uk",Password ="pass"},
                new Developer {LastName = "Danckaert",FirstName = "Emma",Image = "Icon11.png",Skills = new ObservableCollection<Skill>{new Skill{SkillName="C#"},new Skill{SkillName="Javascript"},},AvailableLocations = new ObservableCollection<AvailableLocation>{new AvailableLocation{Province = Province.Antwerpen},new AvailableLocation{Province = Province.VlaamsBrabant},new AvailableLocation{Province = Province.Henegouwen},},Email="feugiat.metus@Donecegestas.co.uk",Password = "pass"},
                new Developer {LastName = "Stavropoulos",FirstName = "Andreas",Image = "Icon12.png",Skills = new ObservableCollection<Skill>{new Skill{SkillName="C#"},new Skill{SkillName=".NET"},},AvailableLocations = new ObservableCollection<AvailableLocation>{new AvailableLocation{Province = Province.Antwerpen},new AvailableLocation{Province = Province.VlaamsBrabant},new AvailableLocation{Province = Province.Henegouwen},},Email="feugiat.metus@Donecegestas.co.uk",Password= "pass"},
                new Developer {LastName = "Van Durme",FirstName = "Pieter",Image = "Icon18.png",Skills = new ObservableCollection<Skill>{new Skill{SkillName="C#"},new Skill{SkillName="Javascript"},},AvailableLocations = new ObservableCollection<AvailableLocation>{new AvailableLocation{Province = Province.Antwerpen},new AvailableLocation{Province = Province.VlaamsBrabant},new AvailableLocation{Province = Province.Henegouwen},},Email = "mi.lacinia@vehicularisusNulla.ca",Password ="pass"},
                new Developer {LastName = "Van Royen",FirstName = "Nick",Image = "Icon19.png",Skills = new ObservableCollection<Skill>{new Skill{SkillName="C#"},new Skill{SkillName=".NET"},},AvailableLocations = new ObservableCollection<AvailableLocation>{new AvailableLocation{Province = Province.Antwerpen},new AvailableLocation{Province = Province.VlaamsBrabant},new AvailableLocation{Province = Province.Henegouwen},},Email ="feugiat.metus@Donecegestas.co.uk",Password = "pass"},
                new Developer {LastName = "Van Yperzele",FirstName = "Diederick",Image = "Icon20.png",Skills = new ObservableCollection<Skill>{new Skill{SkillName="C#"},new Skill{SkillName=".NET"},},AvailableLocations = new ObservableCollection<AvailableLocation>{new AvailableLocation{Province = Province.Antwerpen},new AvailableLocation{Province = Province.VlaamsBrabant},new AvailableLocation{Province = Province.Henegouwen},},Email ="feugiat.metus@Donecegestas.co.uk",Password = "pass"},
                new Developer {LastName = "Verhulsdonck",FirstName = "Marieke",Image = "Icon22.png",Skills = new ObservableCollection<Skill>{new Skill{SkillName="Communication"},},AvailableLocations = new ObservableCollection<AvailableLocation>{new AvailableLocation{Province = Province.Antwerpen},new AvailableLocation{Province = Province.VlaamsBrabant},new AvailableLocation{Province = Province.Henegouwen},},Email ="feugiat.metus@Donecegestas.co.uk",Password = "pass"},
                new Developer {LastName = "Wouters",FirstName = "Michiel",Image = "Icon24.png",Skills = new ObservableCollection<Skill>{new Skill{SkillName="C#"},new Skill{SkillName=".NET"},},AvailableLocations = new ObservableCollection<AvailableLocation>{new AvailableLocation{Province = Province.Antwerpen},new AvailableLocation{Province = Province.VlaamsBrabant},new AvailableLocation{Province = Province.Henegouwen},},Address= "Aalst", Email ="feugiat.metus@Donecegestas.co.uk",Password = "pass"},
                new Developer {LastName = "Cochran", FirstName = "Rudyard", Email = "euismod@tellus.edu", Password = "12448051199", Address = "Ap #280-6118 Placerat Rd.", Skills = new ObservableCollection<Skill>{new Skill{SkillName="C#"},},AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.Luik }, new AvailableLocation { Province = Province.Luxemburg }, }, Image = "Icon03.png",},
                new Developer {LastName = "Hill", FirstName = "Lacota", Email = "Fusce.aliquam.enim@risusDonec.net", Password = "22835770099", Address = "9383 Sit Av.", Skills = new ObservableCollection<Skill>{new Skill{SkillName="C#"},},AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.Antwerpen }, new AvailableLocation { Province = Province.VlaamsBrabant }, },Image = "Icon02.png", },
                new Developer {LastName = "Kennedy", FirstName = "Geraldine", Email = "dignissim@nuncQuisque.org", Password = "22889864199", Address = "Ap #520-5042 Ornare, St.", Skills = new ObservableCollection<Skill>{new Skill{SkillName="HTML"},},AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.Namen }, new AvailableLocation { Province = Province.WaalsBrabant }, }, Image = "Icon03.png",},
                new Developer {LastName = "Lewis", FirstName = "Chaney", Email = "vitae.nibh@semegestas.net", Password = "90336456499", Address = "P.O. Box 495, 1133 Curae; Avenue", Skills = new ObservableCollection<Skill>{new Skill{SkillName="HTML"},},AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.Antwerpen }, new AvailableLocation { Province = Province.VlaamsBrabant }, }, Image = "Icon06.png",},
                new Developer {LastName = "Forbes", FirstName = "Rose", Email = "facilisis.vitae@malesuada.ca", Password = "89611572299", Address = "640 Integer Av.", Skills = new ObservableCollection<Skill>{new Skill{SkillName="C#"},},AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.Luik }, new AvailableLocation { Province = Province.Luxemburg }, },Image = "Icon07.png", },
                new Developer {LastName = "Livingston", FirstName = "Moana", Email = "mi.lacinia@vehicularisusNulla.ca", Password = "29998341199", Address = "5747 Egestas Avenue", Skills = new ObservableCollection<Skill>{new Skill{SkillName="Javascript"},},AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.Namen }, new AvailableLocation { Province = Province.WaalsBrabant }, },Image = "Icon07.png", },
                new Developer {LastName = "Ingram", FirstName = "Valentine", Email = "Vivamus.euismod@nibh.ca", Password = "56994648799", Address = "Ap #791-303 Laoreet Rd.", Skills = new ObservableCollection<Skill>{new Skill{SkillName="HTML"},},AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.Luik }, new AvailableLocation { Province = Province.Luxemburg }, },Image = "Icon03.png", },
                new Developer {LastName = "Mendez", FirstName = "Amber", Email = "Sed@elementumsemvitae.edu", Password = "53922593099", Address = "P.O. Box 756, 7783 Donec Avenue", Skills = new ObservableCollection<Skill>{new Skill{SkillName="C#"},},AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.Antwerpen }, new AvailableLocation { Province = Province.VlaamsBrabant }, },Image = "Icon08.png", },
                new Developer {LastName = "Simpson", FirstName = "Abra", Email = "venenatis.vel.faucibus@duiinsodales.ca", Password = "35324677299", Address = "P.O. Box 759, 4772 Duis Street", Skills = new ObservableCollection<Skill>{new Skill{SkillName="HTML"},},AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.OostVlaanderen }, new AvailableLocation { Province = Province.WestVlaanderen }, },Image = "Icon09.png", },
                new Developer {LastName = "Hicks", FirstName = "Denton", Email = "neque.sed@ultricesVivamus.co.uk", Password = "39321746499", Address = "235-9079 Nec St.", Skills = new ObservableCollection<Skill>{new Skill{SkillName="C#"},},AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.Antwerpen }, new AvailableLocation { Province = Province.VlaamsBrabant }, }, Image = "Icon03.png",},
                new Developer {LastName = "Mason", FirstName = "Madonna", Email = "et.malesuada@anteipsum.edu", Password = "70482048599", Address = "3988 Nec Rd.", Skills = new ObservableCollection<Skill>{new Skill{SkillName="C#"},},AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.OostVlaanderen }, new AvailableLocation { Province = Province.WestVlaanderen }, }, Image = "Icon10.png",},
                new Developer {LastName = "Paul", FirstName = "Ferris", Email = "turpis@Phasellusat.net", Password = "17257348299", Address = "P.O. Box 708, 8046 Sed, St.", Skills = new ObservableCollection<Skill>{new Skill{SkillName="C#"},},AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.Antwerpen }, new AvailableLocation { Province = Province.VlaamsBrabant }, }, Image = "Icon03.png",},
                new Developer {LastName = "Cotton", FirstName = "Stella", Email = "lectus@semperegestasurna.org", Password = "08463167399", Address = "4562 Cras Ave", Skills = new ObservableCollection<Skill>{new Skill{SkillName="C#"},},AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.OostVlaanderen }, new AvailableLocation { Province = Province.WestVlaanderen }, },Image = "Icon05.png", },
                new Developer {LastName = "Graves", FirstName = "Alana", Email = "tempor.lorem.eget@mattissemperdui.co.uk", Password = "35945256799", Address = "221-9223 Dolor, Ave", Skills = new ObservableCollection<Skill>{new Skill{SkillName="C#"},},AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.Namen }, new AvailableLocation { Province = Province.WaalsBrabant }, }, Image = "Icon03.png",},
                new Developer {LastName = "Rollins", FirstName = "Jocelyn", Email = "Ut.semper.pretium@sociisnatoque.org", Password = "16201426199", Address = "854-5493 Cras Avenue", Skills = new ObservableCollection<Skill>{new Skill{SkillName="C#"},},AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.Luik }, new AvailableLocation { Province = Province.Luxemburg }, },Image = "Icon02.png", },
                new Developer {LastName = "Petty", FirstName = "Gay", Email = "hendrerit.consectetuer@pede.net", Password = "10815947299", Address = "205-9573 Class Street", Skills = new ObservableCollection<Skill>{new Skill{SkillName="C#"},},AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.Namen }, new AvailableLocation { Province = Province.WaalsBrabant }, },Image = "Icon11.png", },
                new Developer {LastName = "Kane", FirstName = "MacKensie", Email = "Morbi.accumsan@metusAliquam.net", Password = "00877049099", Address = "727-8141 Mauris St.", Skills = new ObservableCollection<Skill>{new Skill{SkillName="C#"},},AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.Antwerpen }, new AvailableLocation { Province = Province.VlaamsBrabant }, },Image = "Icon03.png", },
                new Developer {LastName = "Lindsay", FirstName = "Marsden", Email = "tincidunt@tinciduntvehicula.org", Password = "25758857699", Address = "143-8587 Lacus. St.", Skills = new ObservableCollection<Skill>{new Skill{SkillName="C#"},},AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.Namen }, new AvailableLocation { Province = Province.WaalsBrabant }, }, Image = "Icon12.png",},
                new Developer {LastName = "Reid", FirstName = "Stacy", Email = "Aenean.euismod.mauris@elitsedconsequat.net", Password = "34458211499", Address = "709-7425 Auctor Rd.", Skills = new ObservableCollection<Skill>{new Skill{SkillName="C#"},},AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.Namen }, new AvailableLocation { Province = Province.WaalsBrabant }, },Image = "Icon13.png", },
                new Developer {LastName = "Rasmussen", FirstName = "Keefe", Email = "lorem.eget.mollis@infaucibusorci.com", Password = "90769592599", Address = "P.O. Box 230, 6308 Felis, Rd.", Skills = new ObservableCollection<Skill>{new Skill{SkillName="HTML"},},AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.OostVlaanderen }, new AvailableLocation { Province = Province.WestVlaanderen }, },Image = "Icon03.png", },
                new Developer {LastName = "Wood", FirstName = "Devin", Email = "et.lacinia.vitae@nuncsedpede.edu", Password = "89203372999", Address = "822-2367 Egestas. Street", Skills = new ObservableCollection<Skill>{new Skill{SkillName="C#"},},AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.Luik }, new AvailableLocation { Province = Province.Luxemburg }, },Image = "Icon01.png", },
                new Developer {LastName = "Cash", FirstName = "Kitra", Email = "natoque@ante.co.uk", Password = "77918828399", Address = "4791 Aenean Ave", Skills = new ObservableCollection<Skill>{new Skill{SkillName="HTML"},},AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.OostVlaanderen }, new AvailableLocation { Province = Province.WestVlaanderen }, },Image = "Icon14.png", },
                new Developer {LastName = "Patrick", FirstName = "Madaline", Email = "metus.facilisis.lorem@Morbinon.com", Password = "28383100499", Address = "654-7913 At St.", Skills = new ObservableCollection<Skill>{new Skill{SkillName="C#"},},AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.Antwerpen }, new AvailableLocation { Province = Province.VlaamsBrabant }, }, Image = "Icon03.png",},
                new Developer {LastName = "Mcclure", FirstName = "Keane", Email = "sem@ultriciesornareelit.edu", Password = "60735984899", Address = "9163 Vitae Rd.", Skills = new ObservableCollection<Skill>{new Skill{SkillName="Javascript"},},AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.Luik }, new AvailableLocation { Province = Province.Luxemburg }, },Image = "Icon15.png", },
                new Developer {LastName = "Hinton", FirstName = "Alea", Email = "interdum.ligula@adipiscing.net", Password = "56760272399", Address = "119-5444 Nunc Ave", Skills = new ObservableCollection<Skill>{new Skill{SkillName="C#"},},AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.Namen }, new AvailableLocation { Province = Province.WaalsBrabant }, },Image = "Icon05.png", },
                new Developer {LastName = "Gross", FirstName = "Bevis", Email = "tristique@est.com", Password = "72677665099", Address = "440-1836 In, Street", Skills = new ObservableCollection<Skill>{new Skill{SkillName="HTML"},},AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.OostVlaanderen }, new AvailableLocation { Province = Province.WestVlaanderen }, }, Image = "Icon02.png",},
                new Developer {LastName = "Hubbard", FirstName = "Edan", Email = "Donec.fringilla.Donec@orciinconsequat.com", Password = "58759579899", Address = "P.O. Box 625, 350 Tempor Road", Skills = new ObservableCollection<Skill>{new Skill{SkillName="C#"},},AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.Luik }, new AvailableLocation { Province = Province.Luxemburg }, }, Image = "Icon03.png",},
                new Developer {LastName = "Patrick", FirstName = "Amena", Email = "Lorem.ipsum.dolor@sit.co.uk", Password = "96906166199", Address = "P.O. Box 303, 563 Nulla St.", Skills = new ObservableCollection<Skill>{new Skill{SkillName="HTML"},},AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.OostVlaanderen }, new AvailableLocation { Province = Province.WestVlaanderen }, },Image = "Icon05.png", },
                new Developer {LastName = "Michael", FirstName = "Norman", Email = "tellus.lorem.eu@tellus.org", Password = "78740551399", Address = "529-8575 Pede. Avenue", Skills = new ObservableCollection<Skill>{new Skill{SkillName="C#"},},AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.Antwerpen }, new AvailableLocation { Province = Province.VlaamsBrabant }, },Image = "Icon06.png", },
                new Developer {LastName = "Head", FirstName = "Imogene", Email = "aptent.taciti@Integerinmagna.edu", Password = "84970731099", Address = "P.O. Box 106, 9802 Erat St.", Skills = new ObservableCollection<Skill>{new Skill{SkillName="Javascript"},},AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.Antwerpen }, new AvailableLocation { Province = Province.VlaamsBrabant }, },Image = "Icon01.png", },
                new Developer {LastName = "Vaughn", FirstName = "Laurel", Email = "feugiat.metus@Donecegestas.co.uk", Password = "43605039299", Address = "6709 Tincidunt Avenue", Skills = new ObservableCollection<Skill>{new Skill{SkillName="C#"},},AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.OostVlaanderen }, new AvailableLocation { Province = Province.WestVlaanderen }, },Image = "Icon16.png", },
                new Developer {LastName = "Chang", FirstName = "Blossom", Email = "est.Mauris.eu@tempusrisusDonec.com", Password = "30330779499", Address = "511-3864 Fermentum St.", Skills = new ObservableCollection<Skill>{new Skill{SkillName="HTML"},},AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.Luik }, new AvailableLocation { Province = Province.Luxemburg }, }, Image = "Icon17.png",},
                new Developer {LastName = "Cole", FirstName = "Laurel", Email = "sit.amet@urnaet.com", Password = "80860411999", Address = "596-8599 Massa. Rd.", Skills = new ObservableCollection<Skill>{new Skill{SkillName="Javascript"},},AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.OostVlaanderen }, new AvailableLocation { Province = Province.WestVlaanderen }, }, Image = "Icon18.png",},
                new Developer {LastName = "Mays", FirstName = "Lee", Email = "commodo.ipsum.Suspendisse@tempusnonlacinia.ca", Password = "84615340399", Address = "997-3063 Turpis St.", Skills = new ObservableCollection<Skill>{new Skill{SkillName="C#"},},AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.Antwerpen }, new AvailableLocation { Province = Province.VlaamsBrabant }, },Image = "Icon19.png", },
                new Developer {LastName = "Madden", FirstName = "Wing", Email = "interdum@Vestibulumante.co.uk", Password = "15656623199", Address = "467-8779 Eleifend Avenue", Skills = new ObservableCollection<Skill>{new Skill{SkillName="HTML"},},AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.OostVlaanderen }, new AvailableLocation { Province = Province.WestVlaanderen }, }, Image = "Icon03.png",},
                new Developer {LastName = "Watkins", FirstName = "Mikayla", Email = "varius.orci.in@pedeblanditcongue.net", Password = "31477040299", Address = "Ap #817-3783 Lacus. Rd.", Skills = new ObservableCollection<Skill>{new Skill{SkillName="C#"},},AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.Namen }, new AvailableLocation { Province = Province.WaalsBrabant }, },Image = "Icon20.png", },
                new Developer {LastName = "Mccall", FirstName = "Brenda", Email = "Quisque.fringilla.euismod@faucibus.com", Password = "93304622699", Address = "5101 Augue St.", Skills = new ObservableCollection<Skill>{new Skill{SkillName="Javascript"},},AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.OostVlaanderen }, new AvailableLocation { Province = Province.WestVlaanderen }, },Image = "Icon21.png", },
                new Developer {LastName = "Hurley", FirstName = "Palmer", Email = "facilisis@nulla.org", Password = "79259451299", Address = "Ap #665-1287 Aliquam Rd.", Skills = new ObservableCollection<Skill>{new Skill{SkillName="C#"},},AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.OostVlaanderen }, new AvailableLocation { Province = Province.WestVlaanderen }, },Image = "Icon22.png", },
                new Developer {LastName = "Berry", FirstName = "Nero", Email = "aliquet.metus@sedleoCras.com", Password = "76298403399", Address = "P.O. Box 427, 4820 Sit Av.", Skills = new ObservableCollection<Skill>{new Skill{SkillName="HTML"},},AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.Luik }, new AvailableLocation { Province = Province.Luxemburg }, },Image = "Icon23.png", },
                new Developer {LastName = "Wyatt", FirstName = "Jakeem", Email = "id.erat@sapienCras.com", Password = "10708721999", Address = "P.O. Box 264, 6751 Malesuada Rd.", Skills = new ObservableCollection<Skill>{new Skill{SkillName="C#"},},AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.OostVlaanderen }, new AvailableLocation { Province = Province.WestVlaanderen }, },Image = "Icon24.png", },
                new Developer {LastName = "Dejesus", FirstName = "Harding", Email = "et.netus@liberolacusvarius.edu", Password = "67452766799", Address = "291-931 Neque Ave", Skills = new ObservableCollection<Skill>{new Skill{SkillName="HTML"},},AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.Antwerpen }, new AvailableLocation { Province = Province.VlaamsBrabant }, }, Image = "Icon03.png",},
                new Developer {LastName = "Harmon", FirstName = "Wyatt", Email = "lacus@Sed.net", Password = "10452611599", Address = "717-8685 Dolor. Rd.", Skills = new ObservableCollection<Skill>{new Skill{SkillName="Javascript"},},AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.OostVlaanderen }, new AvailableLocation { Province = Province.WestVlaanderen }, }, Image = "Icon25.png",},
                new Developer {LastName = "Castro", FirstName = "Anastasia", Email = "at.velit.Cras@orciUtsagittis.net", Password = "37658211099", Address = "P.O. Box 719, 8864 Augue Rd.", Skills = new ObservableCollection<Skill>{new Skill{SkillName="C#"},},AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.Namen }, new AvailableLocation { Province = Province.WaalsBrabant }, },Image = "Icon02.png", },
                new Developer {LastName = "Strickland", FirstName = "Hu", Email = "senectus@maurisblanditmattis.org", Password = "07746731099", Address = "4406 Nibh Road", Skills = new ObservableCollection<Skill>{new Skill{SkillName="C#"},},AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.OostVlaanderen }, new AvailableLocation { Province = Province.WestVlaanderen }, },Image = "Icon26.png", },
                new Developer {LastName = "Hart", FirstName = "Herman", Email = "parturient.montes@egestasblanditNam.org", Password = "50270487999", Address = "302-3117 Metus St.", Skills = new ObservableCollection<Skill>{new Skill{SkillName="HTML"},},AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.OostVlaanderen }, new AvailableLocation { Province = Province.WestVlaanderen }, },Image = "Icon27.png", },
                new Developer {LastName = "Cannon", FirstName = "Calvin", Email = "auctor.quis.tristique@feugiattelluslorem.ca", Password = "73522946299", Address = "253-873 Faucibus. Av.", Skills = new ObservableCollection<Skill>{new Skill{SkillName="C#"},},AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.OostVlaanderen }, new AvailableLocation { Province = Province.WestVlaanderen }, }, Image = "Icon03.png",},
                new Developer {LastName = "Larsen", FirstName = "Emery", Email = "inceptos.hymenaeos@risus.org", Password = "07722152399", Address = "807-1003 Malesuada Road", Skills = new ObservableCollection<Skill>{new Skill{SkillName="C#"},},AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.Luik }, new AvailableLocation { Province = Province.Luxemburg }, },Image = "Icon05.png", },
                new Developer {LastName = "Owens", FirstName = "Bethany", Email = "massa@luctus.com", Password = "36782027099", Address = "715-8767 Faucibus Av.", Skills = new ObservableCollection<Skill>{new Skill{SkillName="Javascript"},},AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.Antwerpen }, new AvailableLocation { Province = Province.VlaamsBrabant }, }, Image = "Icon28.png",},
                new Developer {LastName = "Pacheco", FirstName = "Blaze", Email = "risus@Aliquam.ca", Password = "61804114599", Address = "9764 Eget Rd.", Skills = new ObservableCollection<Skill>{new Skill{SkillName="C#"},},AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.OostVlaanderen }, new AvailableLocation { Province = Province.WestVlaanderen }, },Image = "Icon02.png", },
               };
        }

        private void MakeRecruiterList()
        {
            recruiters = new List<Recruiter>
            {
                new Recruiter {FirstName = "test",LastName = "test",Company = "test",Email = "test",Password = "test", Skills = new ObservableCollection<Skill>{new Skill{SkillName="C#"},},AvailableLocations = new ObservableCollection<AvailableLocation>{new AvailableLocation{Province = Province.Antwerpen},new AvailableLocation{Province = Province.VlaamsBrabant},},Image = "Icon02.png", },
                new Recruiter { LastName = "Levy", FirstName = "Allen", Email = "tristique.senectus.et@blandit.net", Password = "94956578099", Company = "Pulvinar Arcu LLC",AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.OostVlaanderen }, new AvailableLocation { Province = Province.Luxemburg }, },Skills = new ObservableCollection<Skill>{new Skill{SkillName="C#"},},Image = "Icon29.png", },
                new Recruiter { LastName = "Velasquez", FirstName = "Zelenia", Email = "senectus.et.netus@sed.net", Password = "67991704099", Company = "Proin Vel Ltd",AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.Luik }, new AvailableLocation { Province = Province.Henegouwen }, }, Skills = new ObservableCollection<Skill> { new Skill { SkillName = ".NET" }, },Image = "Icon30.png",},
                new Recruiter { LastName = "Aguilar", FirstName = "Avye", Email = "turpis.Aliquam@ligula.ca", Password = "59743482899", Company = "Orci Limited",AvailableLocations = new ObservableCollection<AvailableLocation>{new AvailableLocation{Province = Province.Antwerpen},new AvailableLocation{Province = Province.VlaamsBrabant},},Skills = new ObservableCollection<Skill> { new Skill { SkillName = ".NET" }, },Image = "Icon03.png", },
                new Recruiter { LastName = "Herman", FirstName = "Driscoll", Email = "fringilla.euismod@euenimEtiam.co.uk", Password = "01896711199", Company = "Diam Lorem Auctor Ltd",AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.OostVlaanderen }, new AvailableLocation { Province = Province.Luxemburg }, },Skills = new ObservableCollection<Skill>{new Skill{SkillName="C#"},},Image = "Icon31.png", },
                new Recruiter { LastName = "Webb", FirstName = "Alea", Email = "sem@metusfacilisislorem.com", Password = "94393829099", Company = "Bibendum Corp.",AvailableLocations = new ObservableCollection<AvailableLocation>{new AvailableLocation{Province = Province.Antwerpen},new AvailableLocation{Province = Province.VlaamsBrabant},},Skills = new ObservableCollection<Skill> { new Skill { SkillName = ".NET" }, },Image = "Icon01.png", },
                new Recruiter { LastName = "Head", FirstName = "Geraldine", Email = "ac.tellus.Suspendisse@elementumat.ca", Password = "10427707999", Company = "In Molestie Tortor Inc.",AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.Luik }, new AvailableLocation { Province = Province.Henegouwen }, },Skills = new ObservableCollection<Skill>{new Skill{SkillName="C#"},},Image = "Icon05.png", },
                new Recruiter { LastName = "Walters", FirstName = "Lewis", Email = "est.arcu@odio.co.uk", Password = "49844594199", Company = "In Ornare Sagittis Corporation",AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.OostVlaanderen }, new AvailableLocation { Province = Province.Luxemburg }, },Skills = new ObservableCollection<Skill> { new Skill { SkillName = "Javascript" }, },Image = "Icon15.png", },
                new Recruiter { LastName = "Wolfe", FirstName = "Acton", Email = "et.lacinia@ac.co.uk", Password = "55372032299", Company = "Mauris Sit Amet Industries",AvailableLocations = new ObservableCollection<AvailableLocation>{new AvailableLocation{Province = Province.Antwerpen},new AvailableLocation{Province = Province.VlaamsBrabant},},Skills = new ObservableCollection<Skill>{new Skill{SkillName="C#"},},Image = "Icon16.png", },
                new Recruiter { LastName = "Sosa", FirstName = "Shea", Email = "egestas@auctorodioa.ca", Password = "56652064999", Company = "Ut Quam Corp.",AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.Luik }, new AvailableLocation { Province = Province.Henegouwen }, }, Skills = new ObservableCollection<Skill> { new Skill { SkillName = ".NET" }, },Image = "Icon03.png",},
                new Recruiter { LastName = "Melton", FirstName = "Scarlett", Email = "posuere.cubilia@inaliquet.net", Password = "60507126599", Company = "Faucibus Orci Luctus Incorporated",AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.OostVlaanderen }, new AvailableLocation { Province = Province.Luxemburg }, },Skills = new ObservableCollection<Skill> { new Skill { SkillName = "Javascript" }, },Image = "Icon17.png", },
                new Recruiter { LastName = "Wells", FirstName = "Castor", Email = "vulputate.posuere@luctus.edu", Password = "82592848799", Company = "Arcu Aliquam Consulting",AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.Luik }, new AvailableLocation { Province = Province.Henegouwen }, },Skills = new ObservableCollection<Skill>{new Skill{SkillName="C#"},},Image = "Icon02.png", },
                new Recruiter { LastName = "Winters", FirstName = "Jamal", Email = "feugiat@odio.co.uk", Password = "67478632299", Company = "Ante Dictum Inc.",AvailableLocations = new ObservableCollection<AvailableLocation>{new AvailableLocation{Province = Province.Antwerpen},new AvailableLocation{Province = Province.VlaamsBrabant},},Skills = new ObservableCollection<Skill> { new Skill { SkillName = "HTML" }, },Image = "Icon18.png", },
                new Recruiter { LastName = "Delaney", FirstName = "Devin", Email = "mi.enim.condimentum@Nullam.ca", Password = "37495895799", Company = "Semper Nam Limited",AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.Luik }, new AvailableLocation { Province = Province.Henegouwen }, },Skills = new ObservableCollection<Skill>{new Skill{SkillName="C#"},},Image = "Icon19.png", },
                new Recruiter { LastName = "Nguyen", FirstName = "Hammett", Email = "Integer.eu.lacus@Nullamfeugiat.ca", Password = "28843666799", Company = "Senectus Consulting",AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.OostVlaanderen }, new AvailableLocation { Province = Province.Luxemburg }, },Skills = new ObservableCollection<Skill> { new Skill { SkillName = ".NET" }, },Image = "Icon01.png", },
                new Recruiter { LastName = "Chen", FirstName = "Addison", Email = "id.risus@libero.org", Password = "35944274599", Company = "Consectetuer PC",AvailableLocations = new ObservableCollection<AvailableLocation>{new AvailableLocation{Province = Province.Antwerpen},new AvailableLocation{Province = Province.VlaamsBrabant},},Skills = new ObservableCollection<Skill>{new Skill{SkillName="C#"},},Image = "Icon20.png", },
                new Recruiter { LastName = "Sanchez", FirstName = "Charde", Email = "tempor.augue.ac@semPellentesqueut.net", Password = "88649224999", Company = "Lacinia Mattis LLP",AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.Luik }, new AvailableLocation { Province = Province.Henegouwen }, },Skills = new ObservableCollection<Skill> { new Skill { SkillName = ".NET" }, },Image = "Icon05.png", },
                new Recruiter { LastName = "Dickerson", FirstName = "Rama", Email = "Class.aptent.taciti@acnullaIn.ca", Password = "20861678999", Company = "Sit Inc.",AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.OostVlaanderen }, new AvailableLocation { Province = Province.Luxemburg }, },Skills = new ObservableCollection<Skill>{new Skill{SkillName="C#"},},Image = "Icon21.png", },
                new Recruiter { LastName = "Suarez", FirstName = "Neve", Email = "et@a.org", Password = "83798137199", Company = "Adipiscing Enim LLP",AvailableLocations = new ObservableCollection<AvailableLocation>{new AvailableLocation{Province = Province.Antwerpen},new AvailableLocation{Province = Province.VlaamsBrabant},}, Skills = new ObservableCollection<Skill> { new Skill { SkillName = "Javascript" }, },Image = "Icon06.png",},
                new Recruiter { LastName = "Zimmerman", FirstName = "Lester", Email = "nisi@ornare.edu", Password = "62942022799", Company = "Nisl LLP",AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.OostVlaanderen }, new AvailableLocation { Province = Province.Luxemburg }, },Skills = new ObservableCollection<Skill>{new Skill{SkillName="C#"},},Image = "Icon22.png", },
                new Recruiter { LastName = "Holman", FirstName = "Edan", Email = "ridiculus@condimentumegetvolutpat.org", Password = "53400982899", Company = "Condimentum Corporation",AvailableLocations = new ObservableCollection<AvailableLocation>{new AvailableLocation{Province = Province.Antwerpen},new AvailableLocation{Province = Province.VlaamsBrabant},},Skills = new ObservableCollection<Skill> { new Skill { SkillName = ".NET" }, },Image = "Icon23.png", },
                new Recruiter { LastName = "Juarez", FirstName = "Vladimir", Email = "Vivamus.euismod.urna@aliquetmolestie.org", Password = "43507301599", Company = "Elit Pede Malesuada Institute",AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.Luik }, new AvailableLocation { Province = Province.Henegouwen }, },Skills = new ObservableCollection<Skill> { new Skill { SkillName = ".NET" }, },Image = "Icon24.png", },
                new Recruiter { LastName = "Edwards", FirstName = "Deborah", Email = "augue.eu@dapibusquam.co.uk", Password = "95506781899", Company = "Mattis Cras Foundation",AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.Luik }, new AvailableLocation { Province = Province.Henegouwen }, },Skills = new ObservableCollection<Skill>{new Skill{SkillName="C#"},},Image = "Icon03.png", },
                new Recruiter { LastName = "Dunn", FirstName = "Francis", Email = "orci@necurna.ca", Password = "10739568899", Company = "Euismod LLP",AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.OostVlaanderen }, new AvailableLocation { Province = Province.Luxemburg }, },Skills = new ObservableCollection<Skill>{new Skill{SkillName="C#"},},Image = "Icon25.png", },
                new Recruiter { LastName = "Aguilar", FirstName = "Tiger", Email = "Quisque.libero@eratvolutpat.ca", Password = "39471537799", Company = "Ante Maecenas Mi Corporation",AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.Luik }, new AvailableLocation { Province = Province.Henegouwen }, },Skills = new ObservableCollection<Skill> { new Skill { SkillName = ".NET" }, },Image = "Icon01.png", },
                new Recruiter { LastName = "Schmidt", FirstName = "Chancellor", Email = "tempor.arcu.Vestibulum@parturient.ca", Password = "07716629999", Company = "Faucibus Orci Luctus Foundation",AvailableLocations = new ObservableCollection<AvailableLocation>{new AvailableLocation{Province = Province.Antwerpen},new AvailableLocation{Province = Province.VlaamsBrabant},},Skills = new ObservableCollection<Skill>{new Skill{SkillName="C#"},},Image = "Icon26.png", },
                new Recruiter { LastName = "Riddle", FirstName = "Sloane", Email = "tincidunt@arcu.org", Password = "16598601399", Company = "Metus Urna Convallis PC",AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.OostVlaanderen }, new AvailableLocation { Province = Province.Luxemburg }, },Skills = new ObservableCollection<Skill>{new Skill{SkillName="C#"},},Image = "Icon27.png", },
                new Recruiter { LastName = "Perkins", FirstName = "Noelani", Email = "sem.molestie@tristique.co.uk", Password = "39605497399", Company = "Porttitor Eros Nec Inc.",AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.Luik }, new AvailableLocation { Province = Province.Henegouwen }, },Skills = new ObservableCollection<Skill>{new Skill{SkillName="C#"},},Image = "Icon05.png", },
                new Recruiter { LastName = "Vinson", FirstName = "Steel", Email = "accumsan.interdum.libero@ornare.ca", Password = "98411565099", Company = "Risus At Fringilla Institute",AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.OostVlaanderen }, new AvailableLocation { Province = Province.Luxemburg }, },Skills = new ObservableCollection<Skill>{new Skill{SkillName="C#"},},Image = "Icon28.png", },
                new Recruiter { LastName = "Larsen", FirstName = "Clinton", Email = "nunc.ullamcorper@diamSed.co.uk", Password = "81296332399", Company = "Amet Faucibus Corp.",AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.Luik }, new AvailableLocation { Province = Province.Henegouwen }, },Skills = new ObservableCollection<Skill>{new Skill{SkillName="C#"},},Image = "Icon01.png", },
                new Recruiter { LastName = "Frost", FirstName = "Megan", Email = "et@mattisvelitjusto.co.uk", Password = "70725101099", Company = "Mauris Aliquam Eu Institute",AvailableLocations = new ObservableCollection<AvailableLocation>{new AvailableLocation{Province = Province.Antwerpen},new AvailableLocation{Province = Province.VlaamsBrabant},},Skills = new ObservableCollection<Skill>{new Skill{SkillName="C#"},},Image = "Icon02.png", },
                new Recruiter { LastName = "Vaughan", FirstName = "David", Email = "enim.commodo@ornaresagittisfelis.org", Password = "41571371799", Company = "Elit Sed Consequat LLP",AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.OostVlaanderen }, new AvailableLocation { Province = Province.Luxemburg }, },Skills = new ObservableCollection<Skill> { new Skill { SkillName = ".NET" }, },Image = "Icon29.png", },
                new Recruiter { LastName = "Gardner", FirstName = "Teegan", Email = "est.ac.mattis@purusaccumsaninterdum.ca", Password = "20773365699", Company = "Tortor Integer Aliquam Industries",AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.Luik }, new AvailableLocation { Province = Province.Henegouwen }, },Skills = new ObservableCollection<Skill>{new Skill{SkillName="C#"},},Image = "Icon30.png", },
                new Recruiter { LastName = "Spence", FirstName = "Hanna", Email = "Phasellus@velitegestas.net", Password = "30264719199", Company = "At Pretium Corporation",AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.OostVlaanderen }, new AvailableLocation { Province = Province.Luxemburg }, },Skills = new ObservableCollection<Skill> { new Skill { SkillName = "HTML" }, },Image = "Icon31.png", },
                new Recruiter { LastName = "Daniels", FirstName = "Miriam", Email = "Mauris.vel@utsemNulla.com", Password = "37850223499", Company = "Sed LLP",AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.OostVlaanderen }, new AvailableLocation { Province = Province.Luxemburg }, },Skills = new ObservableCollection<Skill>{new Skill{SkillName="C#"},},Image = "Icon03.png", },
                new Recruiter { LastName = "Medina", FirstName = "Brennan", Email = "urna.et@Donecvitae.com", Password = "93426563899", Company = "Cursus A Enim Company",AvailableLocations = new ObservableCollection<AvailableLocation>{new AvailableLocation{Province = Province.Antwerpen},new AvailableLocation{Province = Province.VlaamsBrabant},},Skills = new ObservableCollection<Skill>{new Skill{SkillName="C#"},},Image = "Icon05.png", },
                new Recruiter { LastName = "Hendricks", FirstName = "Jackson", Email = "malesuada.vel@etnunc.org", Password = "62606734999", Company = "Ac Turpis Incorporated",AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.OostVlaanderen }, new AvailableLocation { Province = Province.Luxemburg }, }, Skills = new ObservableCollection<Skill> { new Skill { SkillName = ".NET" }, },Image = "Icon10.png",},
                new Recruiter { LastName = "Workman", FirstName = "Dillon", Email = "nec.enim.Nunc@Uttincidunt.edu", Password = "69744109799", Company = "Et Eros Corp.",AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.Luik }, new AvailableLocation { Province = Province.Henegouwen }, }, Skills = new ObservableCollection<Skill> { new Skill { SkillName = "Javascript" }, },Image = "Icon01.png",},
                new Recruiter { LastName = "Estrada", FirstName = "Ariana", Email = "aliquet@Vestibulum.edu", Password = "02259836999", Company = "Duis Sit Amet Institute",AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.OostVlaanderen }, new AvailableLocation { Province = Province.Luxemburg }, },Skills = new ObservableCollection<Skill>{new Skill{SkillName="C#"},},Image = "Icon11.png", },
                new Recruiter { LastName = "Mcgee", FirstName = "August", Email = "eros.nec@ligulaNullam.co.uk", Password = "38634632099", Company = "Libero Consulting",AvailableLocations = new ObservableCollection<AvailableLocation>{new AvailableLocation{Province = Province.Antwerpen},new AvailableLocation{Province = Province.VlaamsBrabant},},Skills = new ObservableCollection<Skill> { new Skill { SkillName = ".NET" }, } ,Image = "Icon12.png",},
                new Recruiter { LastName = "Mckee", FirstName = "Clementine", Email = "iaculis.odio.Nam@nullaatsem.co.uk", Password = "35809801299", Company = "Nunc Ltd",AvailableLocations = new ObservableCollection<AvailableLocation>{new AvailableLocation{Province = Province.Antwerpen},new AvailableLocation{Province = Province.VlaamsBrabant},},Skills = new ObservableCollection<Skill> { new Skill { SkillName = ".NET" }, },Image = "Icon13.png", },
                new Recruiter { LastName = "Bowers", FirstName = "Amelia", Email = "In@Maurismolestie.edu", Password = "95262054499", Company = "Id Blandit At Consulting",AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.OostVlaanderen }, new AvailableLocation { Province = Province.Luxemburg }, },Skills = new ObservableCollection<Skill>{new Skill{SkillName="C#"},},Image = "Icon02.png", },
                new Recruiter { LastName = "Mcintosh", FirstName = "Lysandra", Email = "mi.fringilla.mi@pedeblanditcongue.co.uk", Password = "12416526899", Company = "Id Associates",AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.Luik }, new AvailableLocation { Province = Province.Henegouwen }, },Skills = new ObservableCollection<Skill> { new Skill { SkillName = ".NET" }, },Image = "Icon14.png", },
                new Recruiter { LastName = "Clark", FirstName = "Lawrence", Email = "velit.egestas.lacinia@lacusQuisque.edu", Password = "34939201999", Company = "Praesent Eu Nulla Company",AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.OostVlaanderen }, new AvailableLocation { Province = Province.Luxemburg }, },Skills = new ObservableCollection<Skill>{new Skill{SkillName="C#"},},Image = "Icon01.png", },
                new Recruiter { LastName = "Pope", FirstName = "Chava", Email = "dapibus@lacus.com", Password = "90544152099", Company = "Cursus Non PC",AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.Luik }, new AvailableLocation { Province = Province.Henegouwen }, },Skills = new ObservableCollection<Skill>{new Skill{SkillName="C#"},},Image = "Icon15.png", },
                new Recruiter { LastName = "Bradshaw", FirstName = "Clinton", Email = "tincidunt.Donec@utodio.com", Password = "28377314299", Company = "Quisque Porttitor Eros Incorporated",AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.OostVlaanderen }, new AvailableLocation { Province = Province.Luxemburg }, },Skills = new ObservableCollection<Skill> { new Skill { SkillName = ".NET" }, },Image = "Icon16.png", },
                new Recruiter { LastName = "Hopper", FirstName = "Amela", Email = "in@eget.ca", Password = "93268955799", Company = "Lacinia Orci Corp.",AvailableLocations = new ObservableCollection<AvailableLocation>{new AvailableLocation{Province = Province.Antwerpen},new AvailableLocation{Province = Province.VlaamsBrabant},},Skills = new ObservableCollection<Skill> { new Skill { SkillName = ".NET" }, },Image = "Icon05.png", },
                new Recruiter { LastName = "Flowers", FirstName = "Cooper", Email = "vitae.semper.egestas@mollisDuis.org", Password = "09919133499", Company = "Pede Corp.",AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.OostVlaanderen }, new AvailableLocation { Province = Province.Luxemburg }, },Skills = new ObservableCollection<Skill>{new Skill{SkillName="C#"},} ,Image = "Icon06.png",},
                new Recruiter { LastName = "Stark", FirstName = "John", Email = "facilisis.lorem.tristique@metus.com", Password = "54584021699", Company = "Fusce Consulting",AvailableLocations = new ObservableCollection<AvailableLocation>{new AvailableLocation{Province = Province.Antwerpen},new AvailableLocation{Province = Province.VlaamsBrabant},},Skills = new ObservableCollection<Skill> { new Skill { SkillName = ".NET" }, },Image = "Icon03.png", },
                new Recruiter { LastName = "Ellison", FirstName = "Urielle", Email = "lorem.ipsum.sodales@eleifendnecmalesuada.co.uk", Password = "58790026999", Company = "Elit Corp.",AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.OostVlaanderen }, new AvailableLocation { Province = Province.Luxemburg }, },Skills = new ObservableCollection<Skill> { new Skill { SkillName = "HTML" }, },Image = "Icon17.png", },
                new Recruiter { LastName = "Mcpherson", FirstName = "Melanie", Email = "Curabitur.egestas.nunc@malesuada.org", Password = "62890177299", Company = "Mollis Corp.",AvailableLocations = new ObservableCollection<AvailableLocation>{new AvailableLocation{Province = Province.Antwerpen},new AvailableLocation{Province = Province.VlaamsBrabant},}, Skills = new ObservableCollection<Skill>{new Skill{SkillName="C#"},},Image = "Icon05.png",},
                new Recruiter { LastName = "Mclean", FirstName = "Calvin", Email = "habitant@ligulaNullamfeugiat.ca", Password = "25280950899", Company = "Lobortis Risus Institute",AvailableLocations = new ObservableCollection<AvailableLocation> { new AvailableLocation { Province = Province.OostVlaanderen }, new AvailableLocation { Province = Province.Luxemburg }, },Skills = new ObservableCollection<Skill> { new Skill { SkillName = ".NET" }, },Image = "Icon01.png", },
            };
        }

        private void MakeAdminList()
        {
            admins = new List<Admin>
            {
                new Admin
                {
                    Email = "admin",
                    Password = "admin",
                },
            };
        }

        private void MakeSkillList()
        {
            skills = new List<Skill>
            {
                new Skill
                {
                    SkillName = "Banaan",
                    IsCreatedByUser = true,
                },
                new Skill
                {
                    SkillName = "Sleeping",
                    IsCreatedByUser = true,
                },
                new Skill
                {
                    SkillName = ":)",
                    IsCreatedByUser = true,
                },
            };
        }

        public async void AddDummyData()
        {
            BaseViewModel viewModel = new BaseViewModel();
            var temp = new MockData();
            await viewModel.AdminRepo.AddItemsAsync(temp.admins);
            await viewModel.DeveloperRepo.AddItemsAsync(temp.developers);
            await viewModel.RecruiterRepo.AddItemsAsync(temp.recruiters);
            await viewModel.SkillsRepo.AddItemsAsync(temp.skills);
        }
    }
}